services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cobweb_ai:${COBWEB_AI_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      COBWEB_AI_HOST: 0.0.0.0
      COBWEB_AI_DB_HOST: cobweb_ai-db
      COBWEB_AI_DB_PORT: 5432
      COBWEB_AI_DB_USER: cobweb_ai
      COBWEB_AI_DB_PASS: cobweb_ai
      COBWEB_AI_DB_BASE: cobweb_ai

  db:
    image: postgres:16.3-bullseye
    hostname: cobweb_ai-db
    environment:
      POSTGRES_PASSWORD: "cobweb_ai"
      POSTGRES_USER: "cobweb_ai"
      POSTGRES_DB: "cobweb_ai"
    volumes:
      - cobweb_ai-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U cobweb_ai
      interval: 2s
      timeout: 3s
      retries: 40



volumes:
  cobweb_ai-db-data:
    name: cobweb_ai-db-data
